#!/usr/bin/env bash
# 101-tell_the_story_of_passwd
file_h="/etc/passwd"
username=""
groupname=""
homedir=""
shell=""
userid=""
gecos=""
info=""

while IFS= read -r line
do
    username="$(echo "$line" | cut -d":" -f1)"
    groupname="$(echo "$line" | cut -d":" -f4)"
    homedir="$(echo "$line" | cut -d":" -f6)"
    shell="$(echo "$line" | cut -d":" -f7)"
    userid="$(echo "$line" | cut -d":" -f3)"
    gecos="$(echo "$line" | cut -d":" -f2)"
    info="$(echo "$line" | cut -d":" -f5)"

    echo "The user ${username} is part of the ${groupname} gang, lives in ${homedir} and rides ${shell}. ${userid}'s place is protected by the passcode ${gecos}, more info about the user here: ${info}"
done < "$file_h"
